/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
 * Generated on: 10-Apr-2021 23:36:08
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 55
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 55;
const real32_T B[55] = {
   -0.00120295852,-0.002395586576,-0.002043684013,-0.0004744276521, 0.002538748085,
    0.00399729237, 0.002464898862,-0.002276417566, -0.00652201334,-0.006293776445,
  6.722786929e-05, 0.008504665457,  0.01189410593, 0.005225163884,-0.008488573134,
   -0.01879049651,  -0.0148646161, 0.004320009146,  0.02607069165,  0.03089426644,
   0.007909276523, -0.03254078329, -0.05990574881, -0.04085772112,  0.03701286763,
     0.1515255868,   0.2538022101,   0.2947233319,   0.2538022101,   0.1515255868,
    0.03701286763, -0.04085772112, -0.05990574881, -0.03254078329, 0.007909276523,
    0.03089426644,  0.02607069165, 0.004320009146,  -0.0148646161, -0.01879049651,
  -0.008488573134, 0.005225163884,  0.01189410593, 0.008504665457,6.722786929e-05,
  -0.006293776445, -0.00652201334,-0.002276417566, 0.002464898862,  0.00399729237,
   0.002538748085,-0.0004744276521,-0.002043684013,-0.002395586576, -0.00120295852
};
